version: '3.9'
services:
  service-registry:
    image: pavanvarikolu/service-registry:latest
    container_name: service-container
    ports:
      - 8761:8761
    environment:
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_INSTANCE_HOSTNAME=service-registry
      - SERVER_PORT=8761
    networks:
      - quiz-network
    restart: always

  question-db:
    image: postgres:latest
    container_name: question-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=questiondb
    ports:
      - 5432:5432
    volumes:
      - question-db-data:/var/lib/postgresql/data
    networks:
      - quiz-network
    restart: always

  quiz-db:
    image: postgres:latest
    container_name: quiz-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=quizdb
    ports:
      - 5433:5432
    volumes:
      - quiz-db-data:/var/lib/postgresql/data
    networks:
      - quiz-network
    restart: always

  question-service:
    image: pavanvarikolu/question-service:latest
    container_name: question-service-container
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://question-db:5432/questiondb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0000
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - question-db
      - service-registry
    links:
      - service-registry
    networks:
      - quiz-network
    restart: always

  quiz-service:
    image: pavanvarikolu/quiz-service:latest
    container_name: quiz-service-container
    ports:
      - 8090:8090
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://quiz-db:5432/quizdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0000
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - quiz-db
      - service-registry
    links:
      - service-registry
    networks:
      - quiz-network
    restart: always

volumes:
  question-db-data:
  quiz-db-data:

networks:
  quiz-network:
