apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
  namespace: quiz-app-nampespace
  labels:
    app: question-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      name: question-service
      labels:
        app: question-service
    spec:
      containers:
        - name: question-service
          image: pavanvarikolu/question-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: question-service-configmap
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: question-service
spec:
  selector:
    app: question-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
      