apiVersion: v1
kind: ConfigMap
metadata:
  name: quiz-service-config
  namespace: quiz-app-namespace
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://quiz-db:5432/quizdb"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "0000"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-registry:8761/eureka/"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  SPRING_PROFILES_ACTIVE: "docker"
