version: '3.9'
services:
  service-registry:
    build:
      context: ../service-registry
      dockerfile: Dockerfile
    container_name: service-container
    ports:
      - 8761:8761
    networks:
      - quiz-network
    restart: always
  db:
    image: postgres:latest
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=questiondb
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - quiz-network
    restart: always

  question-service:
    build: .
    container_name: question-service-container
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/questiondb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0000
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/
    depends_on:
      - db
      - service-registry
    links:
      - service-registry
    networks:
      - quiz-network
    restart: always

volumes:
  db-data:

networks:
  quiz-network:
